export const BookingdummyData = [
  {
    id: 1,
    title: "Emporium",
    img: require("./bookingpictures/emporium.jpg"),
    description:"Pakistan's largest shopping mall with 300+ brands offering a one stop solution to your needs! ",
    apiName : "F",
    apiBike :"https://fingobox.com/api/database/rows/150/V1aBoEr8U1Kti2PkYkbebN/140",
    apiCar :"https://fingobox.com/api/database/rows/150/V1aBoEr8U1Kti2PkYkbebN/141",
    totalSpots:20,
    bikeTotalSpots:8,
    carTotalSpots:12,
    dataBaseIdBike:140,
    dataBaseRowIdBike:922,
    dataBaseIdCar:141,
    dataBaseRowIdCar:923,

  },
  {
    id: 2,
    title: "Parking and Ride Plaza",
    img: require("./bookingpictures/Park-Ride.png"),
    description:"Parking and Ride Plaza located at 78-D,1 Main Boulevard, Near Liberty Chowk, GulbergIII, Lahore. Main Blvd Gulberg, Lahore 54000, Pakistan.",
    apiName : "F",
    apiBike :"https://fingobox.com/api/database/rows/150/V1aBoEr8U1Kti2PkYkbebN/143",
    apiCar :"https://fingobox.com/api/database/rows/150/V1aBoEr8U1Kti2PkYkbebN/144",
    totalSpots:9,
    bikeSpots:4,
    carSpots:5,
    dataBaseIdBike:143,
    dataBaseRowIdBike:924,
    dataBaseIdCar:144,
    dataBaseRowIdBike:925,
  },
  {
    id: 3,
    title: "LDA Parking Plaza",
    img: require("./bookingpictures/Lda-parking.jpg"),
    description: "71-d-1 Sir Syed Rd, Block D 1 Gulberg III, Lahore, Punjab",
    apiName : "F",
    apiBike :"https://fingobox.com/api/database/rows/150/V1aBoEr8U1Kti2PkYkbebN/145",
    apiCar :"https://fingobox.com/api/database/rows/150/V1aBoEr8U1Kti2PkYkbebN/146",
    totalSpots:15,
    bikeSpots:5,
    carSpots:10,
    dataBaseIdBike:145,
    dataBaseRowIdBike:927,
    dataBaseIdCar:146,
    dataBaseRowIdBike:928,
  },
  {
    id: 4,
    title: "Model Plaza",
    img: require("./bookingpictures/lahore-care.jpeg"),
    description: " Lahore care hospital, Nishtar Town, Lahore, Punjab 54000",
    apiName : "T",
    apiBike :"https://api.thingspeak.com/channels/1995978/fields/1.json?api_key=EY8M8HHPN7CGA5T1&results=1",
    apiCar :"https://api.thingspeak.com/channels/1995978/fields/2.json?api_key=EY8M8HHPN7CGA5T1&results=1",
    totalSpots:5,
    bikeSpots:2,
    carSpots:3,
  },
];
